---
title: "Resume"
format: html
editor: visual
---

chrispleasantstudio\@gmail.com Phone: 540-841-9674

## Work Experience

**Design Assistant, KHIRY -- New York**

July -- September 2021

-   Prototyping, garment construction, and creating detailed, accurate digital tech packs for production.

**Freelance Public Art Ambassador, Times Square Arts**

-- New York July -- September 2021

\- Engaged with the public and facilitated interactive experiences for Times Square Arts' fall public art project.

\- Coordinated special guest visits and performed daily inspections and maintenance for the installation.

**Production Associate, CreateMe -- New York**

July -- September 2023

-   Conducted workshops and presentations on technical equipment such as print and laser-based machinery, embroidery, and direct-to-garment printing.

-   Facilitated pop-up installations to produce customized apparel, footwear, and headwear for events such as the US Tennis Open 2021 & US Surf Open 2021.

-   Generated comprehensive inventory reports and presented findings to management for strategic decision-making. - Acquired proficiency in crafting detailed denim specifications tailored for large-scale manufacturing processes.

**Researcher, Mote Marine Laboratory & Aquarium** -- Florida March 2024 - Analyzed phytoplankton community composition and performed phytopigment analysis using PAM. - Conducted water profiling with CTD instruments and FlowCam to assess environmental factors and diversity.

**Volunteer/Researcher, Billion Oyster Project -- New York**

July -- July 2023 - Collected data on oyster population growth. - Performed shell cleaning to facilitate oyster larvae attachment for population growth.

## Education

**Virginia Commonwealth University**

Bachelor of Fine Arts Cum Laude, Focus in Fashion Design Study Abroad: Portugal (2019), Florence, Italy (2020)

## Skills

-   R Programming
-   Adobe Creative Suite
-   ArcGIS
-   Final Cut Pro
-   Excel
-   Hardware Installation
-   CLO 3D
-   Technical Drawing "
